services:
  web-app:
    build:
      context: ./web-app
    container_name: web-app
    ports:
      - "3000:3000"
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3001:80/tcp"
    environment:
      TZ: 'America/New_York'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    dns:
      - 127.0.0.1

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - pihole
    restart: unless-stopped