services:
  postgres:
    image: postgres:bookworm
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - ./postgres/.env

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - ./pgadmin/.env

  web-app:
    build:
      context: ./web-app
    image: harrymconner/pi-web-app
    container_name: web-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - ./web-app/.env

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3001:80/tcp"
    environment:
      TZ: 'America/New_York'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.1

  nginx:
    build:
      context: ./nginx
    image: harrymconner/pi-nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - pihole
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
