services:
  postgres:
    image: postgres:bookworm
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  web-app:
    build:
      context: ./web-app
    image: harrymconner/pi-web-app
    container_name: web-app
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "3000:3000"
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3001:80/tcp"
    environment:
      TZ: 'America/New_York'
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
    volumes:
      - '~/pi/pihole/etc-pihole:/etc/pihole'
      - '~/pi/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    image: harrymconner/pi-nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - pihole
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
