#!/bin/bash

export BWS_ACCESS_TOKEN=0.43a73ead-5f93-4a61-b0fd-b256001dacb3.qGAu09ouo1qi9bOidGaS26dM2zhgAK:sAQpM8FvVZfW+WPIcvb+1w==

docker compose down

sudo rm -rf pihole

echo y | docker system prune -a --volumes
docker compose pull

bws run --project-id e8cd342b-bca2-4a07-8434-b25600151b46 -- docker compose up -d

docker exec pihole pihole -a -p

sleep 5

sudo sqlite3 pihole/etc-pihole/gravity.db "DELETE FROM adlist WHERE id = 1;"
sudo sqlite3 pihole/etc-pihole/gravity.db "INSERT INTO adlist (address, enabled) VALUES ('https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.plus.txt', 1);"
sudo sqlite3 pihole/etc-pihole/gravity.db "INSERT INTO adlist (address, enabled) VALUES ('https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt', 1);"

docker exec pihole pihole -g
